# Generated by Django 4.2.4 on 2023-11-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('credits', models.PositiveIntegerField()),
                ('students', models.ManyToManyField(to='students.student')),
            ],
        ),
    ]
