# Generated by Django 4.2.4 on 2023-11-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_course_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
